<?php

namespace frontend\controllers;

use common\models\Product;

class CartController extends \yii\web\Controller
{
	private $cart;
	public function init()
	{
		$this->cart = \Yii::$app->cart;
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function actionIndex()
	{
		if ( \Yii::$app->request->isAjax ) {
			return $this->renderAjax("index");
		}
		return $this->render("index");
	}

	public function actionAdd($id, $count = 1)
	{
		try {
			$product = Product::findOne($id);
			if ( $item = $this->cart->getItem($id) ) {
				$this->cart->plus($item->getId(), $count);
			} else {
				$this->cart->add($product, $count);
			}
		} catch (\DomainException $e) {
			\Yii::$app->errorHandler->logException($e);
			\Yii::$app->session->setFlash('error', $e->getMessage());
		}
	}

	public function actionRemove($id)
	{
		try {
			$product = $this->getProduct($id);
			$this->cart->remove($product->id);
		} catch (\DomainException $e) {
			\Yii::$app->errorHandler->logException($e);
			\Yii::$app->session->setFlash('error', $e->getMessage());
		}
		return $this->redirect(['cart/index']);
	}

	private function getProduct($id)
	{
		if ( ($product = Product::findOne((int)$id)) ) {
			return $product;
		}
		throw new \DomainException(\Yii::t("app", "Product not found"));
	}
}