<?php

namespace frontend\modules\api;

class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'frontend\modules\api\controllers';

    public $layout = "main";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}