<?php

namespace frontend\models;

use Yii;

/**
 * @property Staff $staff
 */

class User extends \dektrium\user\models\User
{
	public function beforeDelete()
	{
		if ( $this->staff ) {
			$this->staff->delete();
		}

		return parent::beforeDelete(); // TODO: Change the autogenerated stub
	}

	public function getStaff()
	{
		return $this->hasOne(Staff::className(), ["user_id" => "id"]);
	}

	public static function findByPhone($phone)
	{
		$staff = Staff::findOne(["phone" => $phone]);
		if ( $staff ) {
			return $staff->user;
		}
		return null;
	}

	public static function findByChatId($chat_id)
	{
		$staff = Staff::findOne(["chat_id" => $chat_id]);
		if ( $staff ) {
			return $staff->user;
		}
		return null;
	}

	public static function findByPhoneOrChatId($args)
	{
		$user = self::findByPhone($args);
		if ( !isset($user) ) {
			return $user;
		}
		return self::findByChatId($args);
	}
}